### ISSUE TITLE
在1.14.4版本回档功能无法使用

### ISSUE THREAD

**Issue by Thethumbtack** [TISUnion/QuickBackupM#1]
1.14.4在使用!!qb make并!!qb confirm之后，服务器会关闭，但是并不会回档

**Comment by Fallen-Breath** [comment]
请详细描述下情况，我在本地运行1.14 fabric是没问题的
如果有修改存档文件夹名称记得在代码中及时更改

**Comment by shenjackyuanjie** [comment]
不只是1.14.4 1.15.2也没法用（旧版）没有改动

**Comment by Thethumbtack** [comment]
在运行回档指令后，MCD和服务器会直接关闭，并不会回档，当前解决的办法是删掉server.py第66行代码“sys.exit(0)”（我是MCD1.2.1版本，服务器是1.14.4），就可以回档了

**Comment by Fallen-Breath** [comment]
那可能是MCD的问题？等chino_desu修MCD吧，或者改成我的MCDR

**Comment by shenjackyuanjie** [comment]
另外的话，能不能加一个统一显示帮助信息的插件，现在的话，如果有人不了解这些插件，必须翻源代码看怎么用，如果能加那样的一个插件，可以很好的提升插件的用户体验

**Comment by Fallen-Breath** [comment]
只要知道插件名的话大部分插件用 `!!插件名` 就可以输出帮助信息。如果想要一个连接所有插件的类似 !!help 的命令的话，得等MCDR安排出相关注册帮助信息的接口，并且让其他插件通过他提交自己的帮助信息

**Comment by shenjackyuanjie** [comment]
awa 那，你能不能写一个呢？有的时候真的难受啊
然后，loctions插件也要赶快适配MCDR喽！
