### ISSUE TITLE
无权限玩家输入指令依旧可以执行

### ISSUE THREAD

**Issue by Oveln** [TISUnion/QuickBackupM#10]
`
	# MCDR permission check
	global MinimumPermissionLevel
	if cmd_len >= 2 and command[1] in MinimumPermissionLevel.keys():
		if server.get_permission_level(info) < MinimumPermissionLevel[command[0]]:
			print_message(server, info, '§c权限不足！§r')
			return
`
更改为
`
	# MCDR permission check
	global MinimumPermissionLevel
	if cmd_len >= 2 and command[1] in MinimumPermissionLevel.keys():
		if server.get_permission_level(info) < MinimumPermissionLevel[command[1]]:
			print_message(server, info, '§c权限不足！§r')
			return
`

**Comment by Oveln** [comment]
还有个地方莫得改→_→

**Comment by Fallen-Breath** [comment]
应该已经修好了
