### ISSUE TITLE
1.12版本服务器无法完成备份

### ISSUE THREAD

**Issue by JiMo258** [TISUnion/QuickBackupM#11]
```
[Server] [22:34:29] [Server thread/INFO]: Turned off world auto-saving§r
[Server] [22:34:29] [Server thread/INFO]: Saving...§r
[Server] [22:34:30] [Server thread/INFO]: Saved the world§r
```

以上是Catserver 1.12服务器后台返回的信息， 返回的并非Saved the game导致无法完成备份

**Comment by Fallen-Breath** [comment]
去手动改一下那个判断Saved the game的文本吧，非原版服务端的输出真的不好判断，很难给所有特殊输出的服务端做适配的

**Comment by JiMo258** [comment]
> 去手动改一下那个判断Saved the game的文本吧，非原版服务端的输出真的不好判断，很难给所有特殊输出的服务端做适配的

感谢回复，已经自己改掉了，因为我手头是Catserver的服务器就顺手拿来做例子了，不过1.12.2及以下版本官服应该就是Saved the world，这个应该是固定的。看到没适配就提醒大佬一下233333
