### ISSUE TITLE
备份时，如果备份槽满了的话会报错

### ISSUE THREAD

**Issue by 4O4NtFd** [TISUnion/QuickBackupM#12]
备份失败，错误代码[WinError 5]拒绝访问。：'./qb_multi/slot5\\world'

如果手动删掉slot5则不会出现这个
请问这个怎么处理？
还有回档的时候也是，会显示拒绝访问，任意插槽的都无法回档

**Comment by 4O4NtFd** [comment]
![QQ图片20200701205140](https://user-images.githubusercontent.com/49442853/86250486-376bbf80-bbe3-11ea-8d6a-13939c2c6cc8.png)

**Comment by Fallen-Breath** [comment]
请检查文件权限是否放开

**Comment by 4O4NtFd** [comment]
权限都放开了啊
![001](https://user-images.githubusercontent.com/49442853/86870645-5b5f6180-c10b-11ea-82fe-e5612339a37a.png)
![002](https://user-images.githubusercontent.com/49442853/86870646-5b5f6180-c10b-11ea-8bb6-464c863d8cc5.png)
