### ISSUE TITLE
My server is stagnant

### ISSUE THREAD

**Issue by XSombrio5X** [TISUnion/QuickBackupM#14]
At the time of uploading the backup it is stuck in saving the map and the server does not close at any time. And I have to do CNTL + C to upload the map myself by hand and start the server again. It passes me from 20 attempts 19 times it fails.
![Penene](https://user-images.githubusercontent.com/46429876/98446577-4a087f00-2116-11eb-8f6a-a451f40bdc4b.PNG)

**Comment by XSombrio5X** [comment]
Centos 8.2 64 minimal

Python 3.6.8

Minecraft fabric 1.16.2

MCDReforged 0.9.6

And the latest version to download from QuickBackup

**Comment by Kahzerx** [comment]
this issue was caused by a mod(spark) not letting the server to properly shut down
