### ISSUE TITLE
槽位信息未显示

### ISSUE THREAD

**Issue by MacroModel** [TISUnion/QuickBackupM#16]
!!qb make
[MCDR] [12:01:50] [PT1-on_info@QuickBackupM/INFO]: [QBM] 备份中...请稍等
[Server] [12:01:50] [Server thread/INFO]: Automatic saving is now disabled
[Server] [12:01:50] [Server thread/INFO]: Saving the game (this may take a moment!)
[Server] [12:01:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [12:01:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [12:01:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [12:01:50] [Server thread/INFO]: Saved the game
[MCDR] [12:01:50] [PT1-on_info@QuickBackupM/INFO]: [QBM] 备份完成，耗时0.3秒
[MCDR] [12:01:50] [PT1-on_info@QuickBackupM/INFO]: [QBM] 日期: 2020-11-29 12:01:50; 注释: 空
[Server] [12:01:50] [Server thread/INFO]: Automatic saving is now enabled
!!qb list
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: 【槽位信息】
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位1] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位2] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位3] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位4] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位5] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位6] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位7] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位8] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位9] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: [槽位10] None
[MCDR] [12:02:04] [PT3-on_info@QuickBackupM/INFO]: 备份总占用空间: 9.71 MB

**Comment by shenjackyuanjie** [comment]
emmm 
发一下QBM文件和版本号？

**Comment by Fallen-Breath** [comment]
这个问题是否在当前的版本的 QBM 中仍然存在？如果依然存在，请给出足够详细的能复现此问题的步骤
