### ISSUE TITLE
[功能请求]备份时忽略SQLite文件

### ISSUE THREAD

**Issue by Glucy-2** [TISUnion/QuickBackupM#22]
SQLite3文件在占用时拷贝可能会导致损坏
后缀有`.sqlite`，`.sqlite3`，`.db`，`.sdb`，`.db3`，`.s3db`，`sl3`

**Comment by Fallen-Breath** [comment]
如果备份时忽略了，那恢复时未回复 sqlite 文件是否会出现问题

对于解决方案，为配置文件添加文件名黑名单是否可以解决？

**Comment by Glucy-2** [comment]
SQLite数据库我可以单独备份，应该恢复时不会出现问题
我认为添加文件名黑名单可以解决

**Comment by Fallen-Breath** [comment]
已于 https://github.com/TISUnion/QuickBackupM/releases/tag/v1.4.0 添加该选项
