### ISSUE TITLE
[改进] 优化回档用户体验

### ISSUE THREAD

**Issue by yikerman** [TISUnion/QuickBackupM#31]
QBM原先的回档流程是

1. 创建备份
2. 关闭服务器
3. 拷贝存档
4. 开启服务器

需要较长的时间。如果改成

1. 创建备份
2. 拷贝存档
3. 重启服务器

用户体验会更好一点（尽管总时间是一样的）

**Comment by Fallen-Breath** [comment]
你想在服务器未关闭的时候就拷贝备份覆盖服务器的存档？这是万万不可的
