### ISSUE TITLE
!!qb不备份存档

### ISSUE THREAD

**Issue by nsjsv** [TISUnion/QuickBackupM#32]
[Server] [19:25:12] [Server thread/INFO]: <bug_and_moiang> !!qb make 测试
[Server] [19:25:13] [Server thread/INFO]: Automatic saving is now disabled
[Server] [19:25:13] [Server thread/INFO]: Saving the game (this may take a moment!)
[Server] [19:25:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [19:25:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [19:25:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [19:25:14] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [19:25:14] [Server thread/INFO]: Saved the game
[MCDR] [19:25:14] [QBM - create/INFO] [quick_backup_multi]: copying ./server/world -> ./qb_multi/slot1/world
[MCDR] [19:25:14] [QBM - create/WARNING] [quick_backup_multi]: ./server/world does not exist while copying (./server/world -> ./qb_multi/slot1/world)
[MCDR] [19:25:14] [TaskExecutor/INFO] [timed_quick_backup_multi]: [Timed QBM] 检测到新增的备份，重置定时器
[MCDR] [19:25:14] [TaskExecutor/INFO] [timed_quick_backup_multi]: [Timed QBM] 下次自动备份时间: 2022/05/21 19:55:14
[Server] [19:25:14] [Server thread/INFO]: Automatic saving is now enabled

输入指令后列表正常显示但是存档没有备份

**Comment by nsjsv** [comment]
slot文件夹里只有info.json，没有存档文件夹

**Comment by Fallen-Breath** [comment]
> [MCDR] [19:25:14] [QBM - create/WARNING] [quick_backup_multi]: ./server/world does not exist while copying (./server/world -> ./qb_multi/slot1/world)

请在配置文件中正确填写你存档的路径
