### ISSUE TITLE
存取被拒

### ISSUE THREAD

**Issue by randy20000924** [TISUnion/QuickBackupM#34]
PermissionError: [WinError 5] 存取被拒。: './qb_multi\\slot2\\world\\data'
[MCDR] [23:27:25] [QBM - create/INFO]: [QBM] Back up unsuccessfully, error code [WinError 5] 存取被拒。: './qb_multi\\slot2\\world\\data'

在搭配TimedQBM時發現此問題，在五個slot都存檔後會發生此問題，在刪除任意一個slot裡面的文件後會修復，應該是無法覆蓋的緣故，需要額外加入對特定slot刪除並覆蓋的動作。

**Comment by Fallen-Breath** [comment]
请给出足够详细的能复现此问题的步骤
