### ISSUE TITLE
聊天窗口无法点击指令

### ISSUE THREAD

**Issue by heyibear** [TISUnion/QuickBackupM#36]
mc版本1.19.2 最新MCDR中，运行QBM，在聊天窗口处，点击提示信息无任何反应，比如回档中，提示点击确认，点击后无任何反应，需要自己手动输入confitm指令

**Comment by heyibear** [comment]
找到原因了，原来是RAction.run_command不执行，换成RAction.suggest_command就可以了

**Comment by Fallen-Breath** [comment]
见 https://github.com/Fallen-Breath/MCDReforged/issues/203
