### ISSUE TITLE
在备份期间如果有保存操作会不会写入脏数据？

### ISSUE THREAD

**Issue by luvletter2333** [TISUnion/QuickBackupM#4]
fallen你好，请问如果在备份的时候（时间比较长 150s）如果有保存操作（区块卸载/服务器自动保存），备份文件会写入脏数据吗？

**Comment by Fallen-Breath** [comment]
有可能。不过如果要避免的话得在备份期间关掉自动保存了。如果需要的话可以考虑安排

**Comment by Fallen-Breath** [comment]
20200411这个release加了关闭自动保存这个功能了

**Comment by luvletter2333** [comment]
棒，谢谢Fallen
