### ISSUE TITLE
回档后假人会消失

### ISSUE THREAD

**Issue by saitouhao** [TISUnion/QuickBackupM#44]
备份不能保存GCA的假人文件，回档后假人会消失
希望能增加保存fake_player.gca.json文件的功能

**Comment by OptiJava** [comment]
我认为这是GCA自身特性的问题，gca只有在服务器stop时将假人保存至fake_player.gca.json，备份的时候服务器是在运行中的，假人压根没被保存，没fake_player.gca.json文件。
所以回完档之后没那个文件，也就没自动上线假人，并不是qb没保存fake_player.gca.json，不是qb问题
建议去GCA发issue（

**Comment by Fallen-Breath** [comment]
本插件仅进行文件级别的备份，不理解游戏内的具体机制，请向相关模组负责人进行反馈
