### ISSUE TITLE
在使用新的服务端核心Folia时进行备份似乎无法进行

### ISSUE THREAD

**Issue by TAN-Z-H** [TISUnion/QuickBackupM#46]
更换服务端核心之后，备份槽删除仍可正常进行。但若是进行备份，将会无法进行下去：
[MCDR] [01:22:12] [QBM - create/INFO]: [QBM] 备份中...请稍等
[Server] [01:22:12 INFO]: Automatic saving is now disabled
[Server] [01:22:12 INFO]: Unknown command. Type "/help" for help.

不知道是我的操作问题还是什么原因，也许是个例

**Comment by TAN-Z-H** [comment]
> !!qb make
[MCDR] [01:25:07] [QBM - create/INFO]: [QBM] 正在备份中，请等待操作执行完成

**Comment by shenjackyuanjie** [comment]
能提供更多log吗？

**Comment by TAN-Z-H** [comment]
QBM config文件为默认
MCDR config文件更改了encoding: utf8、decoding: GB2312、handler: bukkit_handler
QBM输入!!qb make 陷入无尽的备份过程中
附上服务端启动到stop的过程：

启动：
C:\MINECRAFT\.minecraft\versions\1.20.1Folia_test>python -m mcdreforged
MCDReforged 2.9.1 is starting up
MCDReforged is open source, u can find it here: https://github.com/Fallen-Breath/MCDReforged
[MCDR] [07:23:40] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [07:23:40] [MainThread/INFO]: 编码 / 解码方式已设置为 utf8 / GB2312
[MCDR] [07:23:40] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [07:23:40] [MainThread/INFO]: - plugins
[MCDR] [07:23:40] [MainThread/INFO]: 解析处理器已设置为 bukkit_handler
[MCDR] [07:23:41] [MainThread/INFO]: MCDReforged正于Python 3.11.3环境中运行
[MCDR] [07:23:41] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [07:23:41] [TaskExecutor/INFO]: 插件 advanced_calculator@0.3.1 已加载
[MCDR] [07:23:41] [TaskExecutor/INFO]: 插件 here@1.2.2 已加载
[MCDR] [07:23:41] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.9.0 已加载
[MCDR] [07:23:41] [TaskExecutor/INFO]: 插件 stats_helper@7.5.1 已加载
[MCDR] [07:23:41] [TaskExecutor/INFO] [here]: 配置文件已加载
[MCDR] [07:23:41] [TaskExecutor/INFO] [quick_backup_multi]: 配置文件已加载
[MCDR] [07:23:41] [TaskExecutor/INFO] [stats_helper]: 配置文件已加载
[MCDR] [07:23:41] [TaskExecutor/INFO] [stats_helper]: UUID list size: 9
[MCDR] [07:23:41] [TaskExecutor/INFO]: 共加载: 4 个插件; 已加载插件数: 6
[MCDR] [07:23:41] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms4G -Xmx8G -jar Folia1.20.1.jar nogui"
[MCDR] [07:23:41] [MainThread/INFO]: 服务端正在以 PID 25020 运行中
[Server] Starting org.bukkit.craftbukkit.Main
[Server] *** Warning, you've not updated in a while! ***
[Server] *** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
[Server] System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190) Host: Windows 11 10.0 (amd64)
[Server] Loading libraries, please wait...
[Server] 2023-06-25 07:23:44,876 ServerMain WARN Advanced terminal features are not available in this environment
[Server] [07:23:57 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com','
[Server] [07:24:01 INFO]: Loaded 7 recipes
[Server] [07:24:02 INFO]: Starting minecraft server version 1.20.1
[Server] [07:24:02 INFO]: Loading properties
[Server] [07:24:02 INFO]: This server is running Kaiiju version git-Kaiiju-"f91b81c" (MC: 1.20.1) (Implementing API ver)
[Server] [07:24:02 INFO]: Server Ping Player Sample Count: 12
[Server] [07:24:02 INFO]: Using 4 threads for Netty based IO
[Server] [07:24:03 WARN]: [!] The timings system cannot be enabled on Folia, and has been scheduled for removal from Pa.
[Server]     We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
[Server]     For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[Server] [07:24:03 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelis
[Server] [07:24:03 INFO]: [io.papermc.paper.threadedregions.TickRegions] Regionised ticking is enabled with 1 tick thres
[Server] [07:24:04 WARN]: SIMD operations are available for your server, but are not configured!
[Server] [07:24:04 WARN]: To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup .
[Server] [07:24:04 WARN]: If you have already added this flag, then SIMD operations are not supported on your JVM or CP.
[Server] [07:24:04 WARN]: Debug: Java: 17.0.6, test run: true
[Server] [07:24:04 INFO]: Default game type: SURVIVAL
[Server] [07:24:04 INFO]: Generating keypair
[Server] [07:24:04 INFO]: Starting Minecraft server on *:25565
[Server] [07:24:04 INFO]: Using default channel type
[Server] [07:24:04 INFO]: Paper: Using Java compression from Velocity.
[Server] [07:24:04 INFO]: Paper: Using Java cipher from Velocity.
[Server] [07:24:06 INFO]: [BlueMap] Loading server plugin BlueMap v3.14
[Server] [07:24:06 INFO]: [BlueMapSignMarkers] Loading server plugin BlueMapSignMarkers v0.0.1
[Server] [07:24:06 INFO]: Server permissions file permissions.yml is empty, ignoring it
[Server] [07:24:06 INFO]: Preparing level "world"
[Server] [07:24:07 INFO]: Preparing start region for dimension minecraft:overworld
[Server] [07:24:07 INFO]: Time elapsed: 23 ms
[Server] [07:24:07 INFO]: Preparing start region for dimension minecraft:the_nether
[Server] [07:24:07 INFO]: Time elapsed: 16 ms
[Server] [07:24:07 INFO]: Preparing start region for dimension minecraft:the_end
[Server] [07:24:07 INFO]: Time elapsed: 15 ms
[Server] [07:24:07 INFO]: [BlueMap] Enabling BlueMap v3.14
[Server] [07:24:07 INFO]: [BlueMap] Loading...
[Server] [07:24:07 INFO]: [BlueMapSignMarkers] Enabling BlueMapSignMarkers v0.0.1
[Server] [07:24:08 INFO]: Done (5.854s)! For help, type "help"
[Server] [07:24:08 INFO]: [BlueMap] Loading resources...
[Server] [07:24:09 INFO]: Initialising world 'world' before it can be ticked...
[Server] [07:24:09 INFO]: Initialised world 'world'
[Server] [07:24:09 INFO]: Timings Reset
[Server] [07:24:10 INFO]: Initialising world 'world_nether' before it can be ticked...
[Server] [07:24:10 INFO]: Initialised world 'world_nether'
[Server] [07:24:10 INFO]: Initialising world 'world_the_end' before it can be ticked...
[Server] [07:24:10 INFO]: Initialised world 'world_the_end'
[Server] [07:24:10 INFO]: [BlueMap] Loading textures...
[Server] [07:24:19 INFO]: [BlueMap] Baking resources...
[Server] [07:24:19 INFO]: [BlueMap] Resources loaded.
[Server] [07:24:19 INFO]: [BlueMap] Loading world 'c8644a57-042a-4f25-8ebb-ec06ffff379b' (C:\MINECRAFT\.minecraft\versi.
[Server] [07:24:19 INFO]: [BlueMap] Initializing Storage: 'file' (Type: FILE)
[Server] [07:24:19 INFO]: [BlueMap] Loading map 'world'...
[Server] [07:24:19 INFO]: [BlueMap] Loading world '1497f6f5-766c-4abb-bc72-5a966db11cc4' (C:\MINECRAFT\.minecraft\versi.
[Server] [07:24:19 INFO]: [BlueMap] Loading map 'world_the_end'...
[Server] [07:24:20 INFO]: [BlueMap] Loading world '566fb37a-75ed-4d07-bb0b-d280dfc0e3aa' (C:\MINECRAFT\.minecraft\versi.
[Server] [07:24:20 INFO]: [BlueMap] Loading map 'world_nether'...
[Server] [07:24:20 INFO]: [BlueMap] WebServer bound to: /[0:0:0:0:0:0:0:0]:8100
[Server] [07:24:20 INFO]: [BlueMap] WebServer started.
[Server] [07:24:20 INFO]: [BlueMap] Loaded!

终止：
[03:56:42] [Server thread/INFO]: Stopping the server
[03:56:42] [Server thread/INFO]: Stopping server
[03:56:42] [Server thread/INFO]: Saving players
[03:56:42] [Server thread/INFO]: Saving worlds
[03:56:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[03:56:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[03:56:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[03:56:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[03:56:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[03:56:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[03:56:46] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by TAN-Z-H** [comment]
不知是否对你分析备份失败原因有所帮助，我尝试更改saved_world_keywords的参数为Saving players以及Saving worlds但是没有效果

**Comment by Fallen-Breath** [comment]
注意到服务端在 QBM 备份触发时输出了此条日志

```
[Server] [01:22:12 INFO]: Unknown command. Type "/help" for help.
```

请确保服务端支持原版的 `/save-all` 等指令，包括 `/sava-all flush`、`save-off`、`/save-on`。若所述服务端不支持这一些指令，会导致 QBM 无法正常工作

以及不要直接复制粘贴日志，这不仅影响阅读，还会导致 github 解析其中的链接，并链接无关的 issue

**Comment by TAN-Z-H** [comment]
明白，今后我会改进反馈方式
