### ISSUE TITLE
[bug] 备份状态有时显示不正确

### ISSUE THREAD

**Issue by OptiJava** [TISUnion/QuickBackupM#49]
复现环境：
Python: `3.11.2`
MCDR: `2.9.1`
插件只安装了qb和mpm，均为最新版
测试用的存档是15.2G

复现方法：
1.控制台输入!!qb make 1，完成后再输入!!qb make 2
![Screenshot_20230713_082350](https://github.com/TISUnion/QuickBackupM/assets/106148777/b109b7b4-368b-4e3c-9592-bc86fb137b51)
2.在`2`备份未完成时，输入!!qb back 1（回档但未确认）
![Screenshot_20230713_082420](https://github.com/TISUnion/QuickBackupM/assets/106148777/11d2a311-3db4-4b24-85d3-716f5d93ffa4)
3.重载插件
4.直到`2`备份被完成，输入!!qb make或!!qb back任意指令，均会显示`【QBM】正在?中，请等待操作执行完成`（玩家在游戏里面打也一样），在`2`备份完成后，恢复正常
![Screenshot_20230713_082615](https://github.com/TISUnion/QuickBackupM/assets/106148777/8d25da67-fbb3-407b-ba54-51a464028860)

想要在备份完成之前跳出这个不正确的状态，只能彻底退出MCDR后重启 或 将插件qb禁用后再启用，其他的!!qb reload、重载插件、热重载mcdr都没有用

（（开世吞的时候要回档了，想提前结束上一次备份赶快回档发现的bug（awa

**Comment by Fallen-Breath** [comment]
这是 QBM 的意料内表现，你无法在备份过程中再次触发备份 / 回档，即便是重载插件也依然如此
