### ISSUE TITLE
其他插件调用!!qb make指令会报错

### ISSUE THREAD

**Issue by Chierin** [TISUnion/QuickBackupM#5]
其他插件执行!!qb make指令会出现server.get_permission_level为NoneType的情况
![image](https://user-images.githubusercontent.com/43374408/79289511-017c4080-7efc-11ea-9e83-bda4b0dc6d96.png)

**Comment by Fallen-Breath** [comment]
你是怎么调用的，参数传了什么

**Comment by Chierin** [comment]
向服务端发送指令!!qb make
server.execute('!!qb make')

**Comment by Fallen-Breath** [comment]
我在之后的版本里关掉了这种检测方式，因为这是MCD1.0里不支持控制台输出指令的一个补救措施。如果需要调用qb的话直接`get_plugin_instance`后调用相关方法就好了
