### ISSUE TITLE
类似#41和#42的问题报告

### ISSUE THREAD

**Issue by TAN-Z-H** [TISUnion/QuickBackupM#50]
使用plain配置参数的时候可以进行正常备份，但是如果使用了tar等压缩格式则无法进行正常备份，进程没有被占用，使用管理员权限无法解决。

log文件如下：
[MCDR.log](https://github.com/TISUnion/QuickBackupM/files/12113033/MCDR.log)

**Comment by Fallen-Breath** [comment]
若想要提供相关信息，请前往 #41 中添加评论，无需再额外开一个 issue
