### ISSUE TITLE
能否兼容Folia端

### ISSUE THREAD

**Issue by hanasaki-misaki** [TISUnion/QuickBackupM#53]
Folia端无法使用QB进行备份
其原因为Folia端禁用了save-all命令
不知道有没有其他办法

**Comment by alex3236** [comment]
不影响啊 只是备份内容不是最新的，并且文件可能在备份过程中被更改（如果autosave依然能关那就更不影响了）

**Comment by Fallen-Breath** [comment]
特殊非原版服务端的问题，无法支持
