### ISSUE TITLE
QBM插件与Luckprems插件prefix功能存在兼容问题

### ISSUE THREAD

**Issue by Leokeyn** [TISUnion/QuickBackupM#61]
你好，在我使用QBM时遇到了一些问题，麻烦向下阅读。

![Snipaste_2024-02-17_15-26-28](https://github.com/TISUnion/QuickBackupM/assets/62866574/853ba3e0-afd2-40d3-9735-749effddc497)
环境：
系统版本: Win10 jdk20 py3.11
QBM版本: QuickBackupM-v1.10.1
服务端版本: Leave(Paper分支)1.20.1

操作步骤：
QBM为默认设置（能够正常在服务端、客户端使用!!qb），服务端安装了LuckPrems插件，我使用/lp user Notch meta addprefix 1 "&c&l[管理员]" 指令来为“Notch”添加前缀（称号）。

错误详情：
进行上述步骤后，在客户端输入!!qb（包括其他MCDR指令）会失效（服务端!!qb不受影响）
因此我认为是QBM与Luckprems的prefix（设置玩家前缀）功能存在兼容问题。
值得一提的是，我尝试更换其他称号插件，在设置玩家前缀（称号）后，均会出现该问题。
![Snipaste_2024-02-17_15-26-28](https://github.com/TISUnion/QuickBackupM/assets/62866574/ad795ea4-1448-44d0-9432-4b7772897619)

**Comment by shenjackyuanjie** [comment]
称号插件会影响服务端的输出，所以要么请关闭称号插件，要么自行编写handler适配

**Comment by Fallen-Breath** [comment]
这是 MCDR 与插件的不兼容，与本插件无关。对于修改玩家名称的非原版插件操作，你需要手动编写 MCDR 的自定义 handler 以适配
