### ISSUE TITLE
控制台可以用，聊天栏不可以

### ISSUE THREAD

**Issue by qfdmcl** [TISUnion/QuickBackupM#63]
![捕获](https://github.com/TISUnion/QuickBackupM/assets/169591233/ae5b020c-3c26-4a38-8fe8-87a884aa3be7)
控制台可以用，聊天栏不可以

**Comment by qfdmcl** [comment]
1.20.4

**Comment by Fallen-Breath** [comment]
这是 MCDR 配置错误，导致 MCDR 无法正确解析玩家信息，导致的。与本插件无关
