### ISSUE TITLE
回档过程中会出现游戏卡死

### ISSUE THREAD

**Issue by Zc1524** [TISUnion/QuickBackupM#64]
我在单人游戏中进行回档操作时，会出现游戏卡死在回档界面的情况，但是回档的结果是没问题的，重启游戏后也是成功的完成了回档
，游戏版本是1.18.2 fabric
我上传了错误报告不知道有没有。
[错误报告-2024-6-13_22.43.53.zip](https://github.com/user-attachments/files/15822483/-2024-6-13_22.43.53.zip)
[错误报告-2024-6-13_22.43.53.zip](https://github.com/user-attachments/files/15822588/-2024-6-13_22.43.53.zip)

**Comment by Fallen-Breath** [comment]
`quickbackupmulti` 模组的问题，与本插件无关。本插件需要 MCDR 运行环境，无法在单人游戏中工作
