### ISSUE TITLE
是否考虑加入定时存档的机制？

### ISSUE THREAD

**Issue by XiaoHuiHui233** [TISUnion/QuickBackupM#9]
QuickBackupM插件非常好用。在之前我是通过自己写了一个简单的复制脚本（python语言）进行世界文件夹的复制，有了QuickBackupM插件，我可以更加智能化，在MC内管理存档和回档。但是我曾经实现的定时进行存档备份的功能在QuickBackupM中并没有具现化的实现。我考虑可能是因为定时存档过于消耗服务器的I/O资源？我简单的修改了QuickBackupM的代码，实现了定时存档的机制，但是代码过于丑陋，我现在正在进行重构工作。不过我想询问一下TIS的大佬们有没有想法加入这个功能？

**Comment by Fallen-Breath** [comment]
见 https://github.com/TISUnion/TimedQBM
